name: Build and scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs docker build 
      - name: Build docker image
        run: docker build -t test:v1 .

      # Aqua Registry login
      - name: Login to Aqua Registry
        uses: docker/login-action@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUADEV_USERNAME }}
          password: ${{ secrets.AQUADEV_PASS }}
      
      
      # Scan the test Image
      - name: Run the scanner 
        run: |
           docker run -d  registry.aquasec.com/scanner:2301.4.11 daemon -e SCALOCK_LOG_LEVEL=DEBUG -e BUILD_JOB_NAME=FRUIT_BANK -e BUILD_NUMBER=${{ github.run_id }}  --token ${{ secrets.TOKEN }} --host ${{secrets.HOST}} test:v1 --no-verify --layer-vulnerabilities --html

