name: Build and scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs docker build 
      - name: Build docker image
        run: docker build -t test:v1 .

      # Aqua Registry login
      - name: Login to Aqua Registry
        uses: docker/login-action@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUADEV_USERNAME }}
          password: ${{ secrets.AQUADEV_PASS }}
      
      
      # Scan the test Image
      - name: Run the scanner 
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --host https://225fccbcb7.cloud.aquasec.com/ --local test:v1 --token ${{ secrets.TOKEN }} --layer-vulnerabilities --no-verify --htmlfile scan-output.html
    
     # Create scan artifact
     - name: Upload Artifact
     uses: actions/upload-artifact@v3
         with:
           name: my-artifact
           path: scan-output.html
           retention-days: 5
     
